name: .NET

on:
  push:
    branches: [ "master" , "MikeTsvirkunovLaba1", "MikeTsvirkunovLaba2" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore XUnit.Coverlet.Collector/ && dotnet restore XUnit.Coverlet.MSBuild/
    - name: Build
      run: cd XUnit.Coverlet.MSBuild/ && dotnet build --no-restore
    - name: Test
      run: cd XUnit.Coverlet.Collector/ && dotnet test --collect:"XPlat Code Coverage"
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
