name: .NET

on:
  push:
    branches: [ "master" , "MikeTsvirkunovLaba1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: cd SaceShips.Lib/ && dotnet build --no-restore
    - name: Test
      run: cd XUnit.Coverlet.Collector/ && dotnet test --collect:"XPlat Code Coverage"
